use techdb;

INSERT hr_empleado (id, codigo_trabajador, codigo_antiguo, nombre, apellido_paterno, apellido_materno, email, id_sexo, foto, direccion, descripcion_zona, referencia_direccion, discapacidad, 
id_tipo_documento, numero_documento, nro_ruc, fecha_nacimiento, fecha_ingreso, fecha_reingreso, fecha_retiro, telefono_alternativo, telefono_fijo, telefono_movil, codigo_sap, pais_emisor, 
id_situacion, id_estado_civil, id_centro_formacion, id_grado_instruccion, id_nacionalidad, id_departamento, id_provincia, id_distrito, id_tipo_trabajador, id_domiciliado, id_situacion_especial, 
id_calendario, sin_control_horario, pendiente_captura, fecha_caducidad_captura, clave_enrolamiento, fecha_ingreso_afp_onp, mas_vida, moneda_calculo, numero_direccion, numero_essalud, 
numero_interior, otros_ingresos_quinta_categoria, sctr, sctr_pension, senati, sindicalizado, tipo_calculo, afiliado_eps, afiliado_essalud, codigo_afp_onp, codigo_cussp, created_date, 
created_by, last_modified_date, last_modified_by, flag_estado, id_sucursal) 
VALUES (16002, NULL, 4534, 'Richard Gustavo', 'Morales', 'Crespo', NULL, 1, NULL, NULL, NULL, NULL, NULL, 1, 42874836, NULL, CAST('2007-10-23 00:00:00.0000000' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', 4, 1, 2, 13, 1, '1', '1', '2', '1', 1, NULL, NULL, NULL, 1, CAST('2017-12-15 00:00:00.0000000' AS DateTime), '1234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST('2017-10-02 16:23:05.0960000' AS DateTime), 'mzorrilla', NULL, NULL, 1, 3601)

INSERT hr_empleado (id, codigo_trabajador, codigo_antiguo, nombre, apellido_paterno, apellido_materno, email, id_sexo, foto, direccion, descripcion_zona, referencia_direccion, discapacidad, id_tipo_documento, numero_documento, nro_ruc, fecha_nacimiento, fecha_ingreso, fecha_reingreso, fecha_retiro, telefono_alternativo, telefono_fijo, telefono_movil, codigo_sap, pais_emisor, id_situacion, id_estado_civil, id_centro_formacion, id_grado_instruccion, id_nacionalidad, id_departamento, id_provincia, id_distrito, id_tipo_trabajador, id_domiciliado, id_situacion_especial, id_calendario, sin_control_horario, pendiente_captura, fecha_caducidad_captura, clave_enrolamiento, fecha_ingreso_afp_onp, mas_vida, moneda_calculo, numero_direccion, numero_essalud, numero_interior, otros_ingresos_quinta_categoria, sctr, sctr_pension, senati, sindicalizado, tipo_calculo, afiliado_eps, afiliado_essalud, codigo_afp_onp, codigo_cussp, created_date, created_by, last_modified_date, last_modified_by, flag_estado, id_sucursal) VALUES (16910, NULL, 555, 'Kelly', 'Onofre', 'Vila', NULL, 2, NULL, NULL, NULL, NULL, NULL, 1, 72215148, NULL, CAST('1992-02-20 00:00:00.0000000' AS DateTime), NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', 4, 1, 3, 13, 1, '01', '1', '1', '1', 1, NULL, NULL, NULL, 1, CAST('2017-12-15 00:00:00.0000000' AS DateTime), '1234', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAST('2017-12-13 00:00:00.0000000' AS DateTime), 'mzorrilla', NULL, NULL, 1, 3601);